### PR TITLE
Update to vertex identifier and label attributes

### PR DESCRIPTION
**Pull request by antares1470**
Values stored in the rdf_identifier vertex attribute are now stored in the identifier attribute
Values that were stored previously in the identifier attribute are now stored in the Label attribute

Consequently, the rdf_identifier vertex attribute has been removed and the key attributes have been adjusted accordingly

Edit: I've also included changes to `resolveVertexType()` which now uses a dominance calculator.

This handles points 9 and 10 of https://github.com/constellation-app/constellation/issues/840#issuecomment-783024094

### CODE REVIEW

**Review by Auriga2 — COMMENTED** [review]
There are 2 parts to it:
1. Populate Label attribute based on the Label triple in the RDF data. Use it's object value as the consty label
2. if there's no label associated with it, use the LocalName of the node's RDF Identifier. (Current value in the Identifier attribute)

Looks like you have only done part 2. You'll probably need to add another if block to catch these label properties. (May be add them in a map and in the edit method, if a label exists, overwrite the default value added in step 2 above or something similar )

Also looks like the  `<Type>`  is missing in the label? Isn't it possible to add here? 

There's another issue when the label has language tags. Which one should we display here! 
E.g.: This node drawn by `http://protege.stanford.edu/ontologies/pizza/pizza.owl`
image

Maybe we can just add the value, without the tag, and keep the `Label` custom attribute, to store details of language tags? Then we don't need to worry about the `Label attribute` when we convert the graph back to the model. (`label custom attribute` should handle that in the https://github.com/constellation-app/constellation-adaptors/pull/12)

**Comment by antares1470** [comment]
Ok I might've misinterpreted exactly what needed to be done there. I'll take a look at adding other part

**Comment by antares1470** [comment]
Ok this PR should now have everything that was requested

**Comment by arcturus2** [comment]
@antares1470 i'll deal with the merge conflicts as I've done that a few times already with other PRs since Friday.

**Pull request merged**
